# Generated by Django 5.0.7 on 2024-07-12 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
